### ISSUE TITLE
[feature]: Add removed domains to the whitelist

### ISSUE THREAD

**Issue by T145** [sefinek24/Sefinek-Blocklist-Collection#18]
Place the domains [removed from other lists](https://github.com/sefinek24/Sefinek-Blocklist-Collection/blob/main/lists/other/Modified%20lists.md) into the whitelist.

**Comment by sefinek** [comment]
Hi. I was thinking earlier about finally dealing with the whitelist, and adding a new feature that would stop domains from being added to the blacklist when a specific one is on the whitelist. This would significantly reduce false positives.

I will implement such a solution soon.

**Comment by sefinek** [comment]
Hello, I am informing you that the whitelist is now ready.

https://github.com/sefinek24/Sefinek-Blocklist-Collection/blob/main/whitelists/main.txt
