### ISSUE TITLE
None of generated list is work

### ISSUE THREAD

**Issue by LexterS999** [sefinek24/Sefinek-Blocklist-Collection#2]
All lists doesn't work. After generating for pi-hole it's saying that list doesn't exist and yest it's true. When I click directly it's saying on Polish language that link doesn't exist. Please fix it.

**Comment by xbc4000** [comment]
Can confirm, have been building my Mikrotik network and decided to re configure my container. Had the lists loaded with over 6 mill domains was aware of the changes watched it slowly start adding back but now gravity just spits out NOT FOUND on all links including from git list and generated list from site.

**Comment by LexterS999** [comment]
Error still not fixed

**Comment by sefinek** [comment]
I apologize for this issue, I will fix it within a few hours. I need to transfer the Node.js applications to my home server. I'm just not sure if my internet will handle it on the second router.

**Comment by LexterS999** [comment]
Cool. I thought that you miss something.

**Comment by sefinek** [comment]
https://blocklist.sefinek.net is now online (:

**Comment by LexterS999** [comment]
Only the first two links for AdGuard are working. All other stuff don't. Even with site generator and especially on GitHub. Still same bug.

**Comment by sefinek** [comment]
Please check again as I just started the Node.js application using [PM2](https://www.npmjs.com/package/pm2).

**Comment by LexterS999** [comment]
Seems like it's working now. Will keep looking on it.
