### ISSUE TITLE
https://blocklist.sefinek.net/ not working

### ISSUE THREAD

**Issue by ronycohen** [sefinek24/Sefinek-Blocklist-Collection#23]
https://blocklist.sefinek.net/ not working

Error 503: Service unavailable

**Comment by sefinek** [comment]
The server ran out of memory again. 40 GB is not enough. I have restored the service. I apologize for the interruption in the website's operation.

![brave_0TNSiWt1qOMR](https://github.com/sefinek24/Sefinek-Blocklist-Collection/assets/92880265/4fa68ac9-d901-417b-b6ce-42ed2d37767f)
