### ISSUE TITLE
List of suggestions for sources of hosts data Gambling (Indonesia) 

### ISSUE THREAD

**Issue by alsyundawy** [sefinek24/Sefinek-Blocklist-Collection#25]
**Which domain(s) should be blocked?**
List of suggestions for sources of hosts data Gambling (Indonesia)

https://github.com/alsyundawy/TrustPositif/raw/main/gambling_indonesia.txt

**Why should these domain(s) be blocked?**
indonesia gambling site update daily & weekly

**Comment by sefinek** [comment]
Added in https://github.com/sefinek24/Sefinek-Blocklist-Collection/commit/e87f37223497a28962b6a5daad7c476a9c27d1bd

Available now in v0.16.0, [changelog](https://blocklist.sefinek.net/changelog)

Thanks.

**Comment by alsyundawy** [comment]
big thx
