### ISSUE TITLE
RPZ & UNBOUND FORMAT

### ISSUE THREAD

**Issue by alsyundawy** [sefinek24/Sefinek-Blocklist-Collection#26]
**please support rpz and unbound format**

**RPZ Format**
```
$TTL 300
@ SOA localhost. root.localhost. 1715037180 43200 3600 259200 300
  NS  localhost.

domain.tld CNAME .
*.domain.tld CNAME .
```

**Unbound Format**
```
server:
local-zone: "domain.tld." always_nxdomain
```

**Comment by sefinek** [comment]
I have preliminarily added support for Unbound and the RPZ format. Thanks.

**RPZ:** https://blocklist.sefinek.net/generated/v1/rpz
**Unbound:** https://blocklist.sefinek.net/generated/v1/unbound

**Comment by sefinek** [comment]
Finished.

**Comment by alsyundawy** [comment]
big thx
