### ISSUE TITLE
Added hostsvn list and removed outdate list

### ISSUE THREAD

**Issue by FiorenMas** [sefinek24/Sefinek-Blocklist-Collection#28]
I noticed you added the hostsVN blocklist:
https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts malicious/bigdargon/hostsVN.fork.txt
in your script:
https://github.com/sefinek24/Sefinek-Blocklist-Collection/blob/main/bash/download.sh
However, this link seems to be outdated. It's been replaced by:
https://github.com/bigdargon/hostsVN/blob/master/extensions/threat/hosts
Additionally, I recommend including this blocklist for blocking ad domains in Vietnam:
https://github.com/bigdargon/hostsVN/blob/master/option/hosts-VN
Thank you for reading!

**Comment by FiorenMas** [comment]
Also, can you push the host files to a separate branch? Pushing your code and bot actions in the same branch makes it hard to read your old commits.

**Comment by sefinek** [comment]
Thank you for these suggestions. I encourage you to create a PR if possible
