### ISSUE TITLE
DNS-Blocklists

### ISSUE THREAD

**Issue by alsyundawy** [sefinek24/Sefinek-Blocklist-Collection#29]
can you add this?

https://github.com/hagezi/dns-blocklists
https://github.com/ShadowWhisperer/BlockLists

**Comment by sefinek** [comment]
It is added
https://github.com/sefinek24/Sefinek-Blocklist-Collection/blob/1e4a3154987eff235303938ee8504716d6bed908/bash/download.sh#L132
https://github.com/sefinek24/Sefinek-Blocklist-Collection/blob/1e4a3154987eff235303938ee8504716d6bed908/bash/download.sh#L27

**Comment by alsyundawy** [comment]
do you typho about space name? url must donnt have space

**Comment by sefinek** [comment]
This is not a further part of the URL, but a path to the file.

pt., 24 maj 2024, 12:48 użytkownik ༺ Initial H ༻ ***@***.***>
napisał:
