### ISSUE TITLE
deselect button 

### ISSUE THREAD

**Issue by alsyundawy** [sefinek24/Sefinek-Blocklist-Collection#36]
can you add deselect button on

https://sefinek.net/blocklist-generator/rpz
https://sefinek.net/blocklist-generator/unnbound

**Comment by sefinek** [comment]
Do you mean a button to deselect all checkboxes?

**Comment by alsyundawy** [comment]
yes exactly

**Comment by sefinek** [comment]
I'll do it right away, because why not. Actually, the checked checkboxes should be saved in cookies

**Comment by sefinek** [comment]
The update is now in production. I have added the button you requested. Additionally, checkboxes are now saved in cookies. I also added a few lines of CSS to prevent checkboxes from being selected, for example, by double-clicking the left mouse button
