### ISSUE TITLE
change url generator 

### ISSUE THREAD

**Issue by alsyundawy** [sefinek24/Sefinek-Blocklist-Collection#40]
please change url 

from
https://blocklist.sefinek.net/generated/v1/

to 
https://raw.githubusercontent.com/sefinek24/Sefinek-Blocklist-Collection/main/blocklists/generated/

becaouse 

1. Cloudflare cache proxy not update list
2. your website slow , better than from github

**Comment by sefinek** [comment]
Absolutely, that will never happen. Cloudflare doesn't cache this; I have verified it multiple times. The last synchronization took place on 2024-06-22 at 05:30:01 and was successfully completed at 2024-06-22 at 05:30:12. The site continues to display the latest version of the lists without requiring a server restart. This process is automated and runs smoothly, ensuring that all updates are promptly reflected on the website.

Regarding the second point you mentioned, I must admit I was a bit surprised. The site is functioning normally and has been stable. Please double-check your internet connection, as connectivity issues on your end might cause the problems you’re experiencing. So far, you are the first person out of nearly a thousand users to report such an issue. I have not received any similar complaints, and all my monitoring systems indicate that everything is operating as expected.

It's also important to remember that blocklist.sefinek.net is not a CDN (Content Delivery Network) server! To clarify, blocklist.sefinek.net is hosted on OVH servers located in Warsaw.

I would also kindly ask you not to spam issues, as it is somewhat frustrating. Thanks (:

Video: https://github.com/sefinek24/Sefinek-Blocklist-Collection/assets/92880265/7f392155-2a8a-4d8a-b1bc-86d39f318daf
![WindowsTerminal_J2APLZkLW4Fy](https://github.com/sefinek24/Sefinek-Blocklist-Collection/assets/92880265/68b7a6a6-8392-4555-af6c-f172cdd8bc3e)
![brave_kuSAm03PkqtA](https://github.com/sefinek24/Sefinek-Blocklist-Collection/assets/92880265/8d8ebe08-498b-42e4-92e4-4b5e1417d231)
