### ISSUE TITLE
ShadowWhisperer BlockLists

### ISSUE THREAD

**Issue by alsyundawy** [sefinek24/Sefinek-Blocklist-Collection#43]
https://github.com/ShadowWhisperer/BlockLists

**Comment by sefinek** [comment]
Currently, only one list from the ShadowWhisperer/BlockLists repository is being used. I will implement more here soon, thanks
https://github.com/sefinek24/Sefinek-Blocklist-Collection/blob/4b68b8f3720a85ff56518136bf4a9875dbd656cc/bash/download.sh#L27
