### ISSUE TITLE
new porn domain

### ISSUE THREAD

**Issue by alsyundawy** [sefinek24/Sefinek-Blocklist-Collection#45]
https://github.com/Bon-Appetit/porn-domains

**Comment by sefinek** [comment]
### [README.md](https://github.com/Bon-Appetit/porn-domains/blob/master/README.md):
_The repository has undergone extensive validation of domains with careful DNS checks to minimize the potential for false results. Nevertheless, it's crucial to acknowledge that circumstances can evolve swiftly. Please be aware that this list does not come with any guarantee of accuracy. Exercise caution, especially for critical applications._

**Comment by alsyundawy** [comment]
https://raw.githubusercontent.com/Bon-Appetit/porn-domains/master/block.txt
