### ISSUE TITLE
Enjoy the report! <3

### ISSUE THREAD

**Issue by ghost** [sefinek24/Sefinek-Blocklist-Collection#46]
reported for being a bigoted piece of shit <3 hope you enjoy your ban!

**Comment by sefinek24** [comment]
Oh, I think I might have hurt someone's ego :c
However, it seems you don't quite understand how bans work on GitHub. I'm so sorry 😢 😞

**Comment by sefinek24** [comment]
my honest reaction:
https://github.com/user-attachments/assets/b46c8d4d-8e35-4913-8e07-08cbb7ddba70

**Comment by 4risu** [comment]
Your behaviour will only help Github to make the right decision (banning you for hate speech)

**Comment by sefinek24** [comment]
@4risu
I didn't know that expressing one's views is considered hate speech. You must be living in an alternate world bro :D
