### ISSUE TITLE
Tiny Correction

### ISSUE THREAD

**Issue by ghost** [sefinek24/Sefinek-Blocklist-Collection#5]
Thank you for putting in effort to create this collection. I started using pi-hole today and installed your lists from your site (cool design btw).

There is a tiny correction needed in the project's readme where in the Information section's Note, the hyperlink for "default blocklist" is "https://github.com/sefinek24/lists/Index.md", instead of "https://github.com/sefinek24/Sefinek-Blocklist-Collection/blob/main/lists/Index.md". 

I know it is annoying to point out such things, and it is not my intention to do that.

Thank you once again 😸

**Comment by sefinek** [comment]
Thanks for letting me know about this. It was a GitHub bug because when I removed `> **Note**` the issue with the incorrect redirection stopped.
