### ISSUE TITLE
Bigoted list

### ISSUE THREAD

**Issue by Lumb-Chul** [sefinek24/Sefinek-Blocklist-Collection#57]
Dude, what is wrong with you. Why would you make your project political with the inclusion of LGBTQ+ label. The point of Ad blockers is to protect personal information and prevent companies from profiting off of you, not to be bigoted. Keep blocked sites on your own private repo.

**Comment by sefinek24** [comment]
Why are you so upset?

I'm not bringing politics into this - I'm just expressing my opinion, which I have every right to do. No one will limit or forbid that for me. Your actions just make it clear that you lean left.

I completely disagree with you. Pi-hole and AdGuard Home are not just ad blockers. The Pi-hole developers changed the phrase `Domain on Adlists` to `Domain on Lists` in version 6. Pi-hole v5 is still being used for various purposes.
**Old version (v5):**
![image](https://github.com/user-attachments/assets/14e4c2c4-99db-48bd-8c4e-feaa44f72bdd)

**Beta (v6):**
![image](https://github.com/user-attachments/assets/e176d927-4864-44b4-ba55-c6a12b747043)

I really don't understand where your outrage is coming from. That's just how leftists are, nothing new... It's a shame our world is falling apart, but oh well. Nothing can be done about it. If someone doesn't want to block LGBTQ+ sites, they simply don't have to. Just uncheck the checkbox in the generator on my site, and that's it. What's the problem?

More info:
https://github.com/sefinek24/Sefinek-Blocklist-Collection/discussions/47#discussioncomment-10137929
https://blocklist.sefinek.net/viewer/info/block/LGBTQ_Plus

Good bless you! ✝
