### ISSUE TITLE
blocklist.sefinek.net is dead (for me anyway)

### ISSUE THREAD

**Issue by Thorpy** [sefinek24/Sefinek-Blocklist-Collection#63]
I figured you might want to know that Cloudflare is 502 bad gatewaying https://blocklist.sefinek.net/ causing adlists to stop updating

**Comment by sefinek** [comment]
I unnecessarily updated [Express.js](https://github.com/expressjs/express/releases/tag/v5.0.0) to the latest version (v5) yesterday. Thanks for reporting this, I will keep monitoring the server's status.

**Comment by sefinek** [comment]
I've made several changes to file serving. The server is functioning properly. Closing
https://github.com/sefinek24/Sefinek-Blocklist-Collection/blob/main/www/routes/Blocklists/Main.js
