### ISSUE TITLE
duplicated domain

### ISSUE THREAD

**Issue by alsyundawy** [sefinek24/Sefinek-Blocklist-Collection#65]
duplicate list on 

https://blocklist.sefinek.net/generated/v1/rpz/social/tiktok.txt

then can check all list you have when remove duplicated

**Comment by sefinek** [comment]
I don't quite understand what you mean 🤔

**Comment by alsyundawy** [comment]
do you check duplicated record on tiktok.txt?

**Comment by alsyundawy** [comment]
```
#!/bin/bash

# URL of the file
URL="https://blocklist.sefinek.net/generated/v1/rpz/social/tiktok.txt"

# Download the file and remove duplicates without sorting
curl -s "$URL" | awk '!seen[$0]++' > tiktok_cleaned.txt

echo "Duplicates removed and cleaned file saved as tiktok_cleaned.txt"
```

**Comment by sefinek** [comment]
![image](https://github.com/user-attachments/assets/ff3647a1-5be8-40cf-ac90-74d02a013c46)
There are no duplicates here

**Comment by sefinek** [comment]
Indeed, the RPZ had duplicate lines, thanks for pointing that out. I fixed it, although I really didn't have the desire and time

https://github.com/sefinek24/Sefinek-Blocklist-Collection/commit/882ce9999323c62da75e2e5054fe981a8d0157d0
