### ISSUE TITLE
Connection Timeout since last Update

### ISSUE THREAD

**Issue by S2ciOnur** [sefinek24/Sefinek-Blocklist-Collection#73]
First of all, I would like to thank you for this project.
Unfortunately, there has been a problem since the last update.
My Gravity list updates Saturday night. This morning I noticed that the generated URLs to the blocklists are running on timeouts:
![image](https://github.com/user-attachments/assets/f8e7e24c-61ad-4b13-99c5-15a5809eddf5)

**Comment by sefinek** [comment]
Thanks, and sorry about that. Look #72

**Comment by S2ciOnur** [comment]
It looks like https://sefinek.net with all subdomains are reachable but https://blocklist.sefinek.net
I'll donate also.
When could it be available again?

**Comment by sefinek** [comment]
The site blocklist.sefinek.net was hosted on a VPS I purchased from OVH, while my other sites are hosted from my home. This specific site handles over 70k requests daily, so hosting it at home would severely strain my network. Even if I attempted to host it here, users from regions like the US would likely experience slow download speeds. my ISP only provides 300Mb/s UL bandwidth. In that case, I would need to rely on CF's cache, but it wouldn’t be a perfect solution 

Answered on Discord, closing

**Comment by 833M0L3** [comment]
Hi @sefinek24 , I was wondering why you are not using GitHub raw URLs to directly serve the blocklist txt files instead of serving via VPS. Github allows 500-600 req per user in a day until they are rate limited which is enough. This guy here does something similar but uses Github [Toolspack](https://github.com/Azathothas/Toolpacks). If you like to talk more to make this more manageable, let's talk. We have a telegram group https://t.me/official_loonix

**Comment by sefinek** [comment]
@833M0L3, gitHub occasionally performs poorly in my region, which is one reason for adopting this approach.

The second reason is that I want to collect some statistics.

Additionally, I want the lists to synchronize only at night from the main branch. In the main repository, lists are updated every two hours. This schedule allows me to remove false positives before they go into production. I realize this could be done with two branches, but that would make the repository too large. As I mentioned, every few days, GitHub's performance in my region is noticeably slow

**Comment by 833M0L3** [comment]
@sefinek24 We have VPS and bucket stuffs , hop over to https://t.me/official_loonix , we can talk more

**Comment by sefinek** [comment]
@833M0L3 Thank you, but I'm not interested

**Comment by sefinek24** [comment]
The blocklist at [blocklist.sefinek.net](https://blocklist.sefinek.net) is now operational.

**Comment by sefinek** [comment]
The website at [blocklist.sefinek.net](https://blocklist.sefinek.net) has now been fully restored and is fully operational.

**Comment by 833M0L3** [comment]
@sefinek Glad it's back online. It's even faster now.
