### ISSUE TITLE
[FALSE POSITIVE] arquivo.pt is being classified as a phishing site

### ISSUE THREAD

**Issue by luisccgoncalves** [sefinek24/Sefinek-Blocklist-Collection#75]
Hello!

The domain arquivo.pt is present on the [phishing blocklist](https://blocklist.sefinek.net/generated/0.0.0.0/forks/blocklistproject.phishing.txt).

This is a Portuguese non-profit project to archive Portuguese language websites, analogous to archive.org.

**Comment by sefinek** [comment]
Thanks, within 24h the domain will be removed from `phishing/blocklistproject/phishing.fork.txt`.
